/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elevator;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author rob
 */
public class ElevatorMain extends javax.swing.JFrame
{
    ImageIcon logo = new javax.swing.ImageIcon(getClass().getResource("/elevator/logo.png"));
    
    /**
     * Creates new form ElevatorMain
     */
    public ElevatorMain()
    {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        mainPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        topLeftPanel = new logoPanel();
        topRightPanel = new javax.swing.JPanel();
        upperTopRightPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        innerLeftPanel = new javax.swing.JPanel();
        eightButton = new javax.swing.JButton();
        sevenButton = new javax.swing.JButton();
        sixButton = new javax.swing.JButton();
        fiveButton = new javax.swing.JButton();
        fourButton = new javax.swing.JButton();
        threeButton = new javax.swing.JButton();
        twoButton = new javax.swing.JButton();
        oneButton = new javax.swing.JButton();
        innerCenterPanel = new innerCenterPanel();
        innerRightPanel = new javax.swing.JPanel();
        speedSlider = new javax.swing.JSlider();
        bottomPanel = new javax.swing.JPanel();
        bottomLeftPanel = new javax.swing.JPanel();
        floorComboBox = new javax.swing.JComboBox();
        bottomCenterPanel = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        bottomRightPanel = new javax.swing.JPanel();
        colourButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        mainPanel.setLayout(new java.awt.BorderLayout());

        topPanel.setBackground(new java.awt.Color(153, 204, 255));
        topPanel.setLayout(new java.awt.BorderLayout());

        topLeftPanel.setBackground(new java.awt.Color(153, 153, 153));
        topLeftPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout topLeftPanelLayout = new javax.swing.GroupLayout(topLeftPanel);
        topLeftPanel.setLayout(topLeftPanelLayout);
        topLeftPanelLayout.setHorizontalGroup(
            topLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        topLeftPanelLayout.setVerticalGroup(
            topLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        topPanel.add(topLeftPanel, java.awt.BorderLayout.WEST);

        topRightPanel.setBackground(new java.awt.Color(255, 255, 204));
        topRightPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        topRightPanel.setLayout(new java.awt.BorderLayout(0, 2));

        upperTopRightPanel.setBackground(new java.awt.Color(153, 204, 255));
        upperTopRightPanel.setPreferredSize(new java.awt.Dimension(50, 70));
        upperTopRightPanel.setLayout(new java.awt.GridLayout());

        jLabel1.setFont(new java.awt.Font("Nyala", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Elevator Simulator");
        upperTopRightPanel.add(jLabel1);

        topRightPanel.add(upperTopRightPanel, java.awt.BorderLayout.NORTH);

        statusLabel.setForeground(new java.awt.Color(102, 102, 102));
        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusLabel.setText("Picking up [3] passengers on level [6]");
        topRightPanel.add(statusLabel, java.awt.BorderLayout.CENTER);

        topPanel.add(topRightPanel, java.awt.BorderLayout.CENTER);

        mainPanel.add(topPanel, java.awt.BorderLayout.NORTH);

        centerPanel.setBackground(new java.awt.Color(51, 255, 51));
        centerPanel.setPreferredSize(new java.awt.Dimension(465, 200));
        centerPanel.setLayout(new java.awt.BorderLayout());

        innerLeftPanel.setBackground(new java.awt.Color(153, 153, 153));
        innerLeftPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        innerLeftPanel.setPreferredSize(new java.awt.Dimension(100, 100));
        innerLeftPanel.setLayout(new java.awt.GridLayout(8, 0, 0, 5));

        eightButton.setBackground(new java.awt.Color(102, 102, 102));
        eightButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eightButton.setForeground(new java.awt.Color(255, 255, 255));
        eightButton.setText("8");
        eightButton.setBorderPainted(false);
        innerLeftPanel.add(eightButton);

        sevenButton.setBackground(new java.awt.Color(102, 102, 102));
        sevenButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sevenButton.setForeground(new java.awt.Color(255, 255, 255));
        sevenButton.setText("7");
        sevenButton.setBorderPainted(false);
        innerLeftPanel.add(sevenButton);

        sixButton.setBackground(new java.awt.Color(102, 102, 102));
        sixButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sixButton.setForeground(new java.awt.Color(255, 255, 255));
        sixButton.setText("6");
        sixButton.setBorderPainted(false);
        innerLeftPanel.add(sixButton);

        fiveButton.setBackground(new java.awt.Color(102, 102, 102));
        fiveButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fiveButton.setForeground(new java.awt.Color(255, 255, 255));
        fiveButton.setText("5");
        fiveButton.setBorderPainted(false);
        innerLeftPanel.add(fiveButton);

        fourButton.setBackground(new java.awt.Color(102, 102, 102));
        fourButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fourButton.setForeground(new java.awt.Color(255, 255, 255));
        fourButton.setText("4");
        fourButton.setBorderPainted(false);
        innerLeftPanel.add(fourButton);

        threeButton.setBackground(new java.awt.Color(102, 102, 102));
        threeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        threeButton.setForeground(new java.awt.Color(255, 255, 255));
        threeButton.setText("3");
        threeButton.setBorderPainted(false);
        innerLeftPanel.add(threeButton);

        twoButton.setBackground(new java.awt.Color(102, 102, 102));
        twoButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        twoButton.setForeground(new java.awt.Color(255, 255, 255));
        twoButton.setText("2");
        twoButton.setBorderPainted(false);
        innerLeftPanel.add(twoButton);

        oneButton.setBackground(new java.awt.Color(102, 102, 102));
        oneButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        oneButton.setForeground(new java.awt.Color(255, 255, 255));
        oneButton.setText("1");
        oneButton.setBorderPainted(false);
        innerLeftPanel.add(oneButton);

        centerPanel.add(innerLeftPanel, java.awt.BorderLayout.WEST);

        innerCenterPanel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout innerCenterPanelLayout = new javax.swing.GroupLayout(innerCenterPanel);
        innerCenterPanel.setLayout(innerCenterPanelLayout);
        innerCenterPanelLayout.setHorizontalGroup(
            innerCenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );
        innerCenterPanelLayout.setVerticalGroup(
            innerCenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );

        centerPanel.add(innerCenterPanel, java.awt.BorderLayout.CENTER);

        innerRightPanel.setBackground(new java.awt.Color(255, 255, 204));
        innerRightPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        innerRightPanel.setPreferredSize(new java.awt.Dimension(80, 100));
        innerRightPanel.setLayout(new java.awt.GridLayout());

        speedSlider.setBackground(new java.awt.Color(51, 255, 0));
        speedSlider.setForeground(new java.awt.Color(0, 102, 102));
        speedSlider.setMajorTickSpacing(10);
        speedSlider.setMinorTickSpacing(5);
        speedSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        speedSlider.setPaintLabels(true);
        speedSlider.setPaintTicks(true);
        speedSlider.setSnapToTicks(true);
        speedSlider.setOpaque(false);
        innerRightPanel.add(speedSlider);

        centerPanel.add(innerRightPanel, java.awt.BorderLayout.EAST);

        mainPanel.add(centerPanel, java.awt.BorderLayout.CENTER);

        bottomPanel.setBackground(new java.awt.Color(0, 153, 153));
        bottomPanel.setPreferredSize(new java.awt.Dimension(200, 50));
        bottomPanel.setLayout(new java.awt.BorderLayout());

        bottomLeftPanel.setBackground(new java.awt.Color(153, 153, 153));
        bottomLeftPanel.setPreferredSize(new java.awt.Dimension(100, 100));
        bottomLeftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        floorComboBox.setBackground(new java.awt.Color(242, 242, 242));
        floorComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "8 Floors", "7 Floors", "6 Floors", "5 Floors", "4 Floors", "3 Floors", "2 Floors" }));
        floorComboBox.setPreferredSize(new java.awt.Dimension(20, 20));
        bottomLeftPanel.add(floorComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        bottomPanel.add(bottomLeftPanel, java.awt.BorderLayout.WEST);

        bottomCenterPanel.setBackground(new java.awt.Color(123, 119, 123));
        bottomCenterPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        bottomCenterPanel.setPreferredSize(new java.awt.Dimension(500, 500));
        bottomCenterPanel.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        startButton.setBackground(new java.awt.Color(153, 153, 153));
        startButton.setForeground(new java.awt.Color(255, 255, 255));
        startButton.setText("Start");
        startButton.setBorderPainted(false);
        bottomCenterPanel.add(startButton);

        stopButton.setBackground(new java.awt.Color(138, 138, 138));
        stopButton.setForeground(new java.awt.Color(255, 255, 255));
        stopButton.setText("Stop");
        stopButton.setBorderPainted(false);
        bottomCenterPanel.add(stopButton);

        bottomPanel.add(bottomCenterPanel, java.awt.BorderLayout.CENTER);

        bottomRightPanel.setBackground(new java.awt.Color(102, 102, 102));
        bottomRightPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        bottomRightPanel.setPreferredSize(new java.awt.Dimension(200, 50));
        bottomRightPanel.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        colourButton.setBackground(new java.awt.Color(0, 51, 102));
        colourButton.setForeground(new java.awt.Color(255, 255, 255));
        colourButton.setText("Colour");
        colourButton.setBorderPainted(false);
        bottomRightPanel.add(colourButton);

        quitButton.setBackground(new java.awt.Color(204, 0, 51));
        quitButton.setForeground(new java.awt.Color(255, 255, 255));
        quitButton.setText("Quit");
        quitButton.setBorderPainted(false);
        bottomRightPanel.add(quitButton);

        bottomPanel.add(bottomRightPanel, java.awt.BorderLayout.EAST);

        mainPanel.add(bottomPanel, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ElevatorMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomCenterPanel;
    private javax.swing.JPanel bottomLeftPanel;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel bottomRightPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JButton colourButton;
    private javax.swing.JButton eightButton;
    private javax.swing.JButton fiveButton;
    private javax.swing.JComboBox floorComboBox;
    private javax.swing.JButton fourButton;
    private javax.swing.JPanel innerCenterPanel;
    private javax.swing.JPanel innerLeftPanel;
    private javax.swing.JPanel innerRightPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton oneButton;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton sevenButton;
    private javax.swing.JButton sixButton;
    private javax.swing.JSlider speedSlider;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JButton stopButton;
    private javax.swing.JButton threeButton;
    private javax.swing.JPanel topLeftPanel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JPanel topRightPanel;
    private javax.swing.JButton twoButton;
    private javax.swing.JPanel upperTopRightPanel;
    // End of variables declaration//GEN-END:variables

    // Custom inner class to represent the middle panel.
    // Elevator animation will occur in the overriden paint function.
    class innerCenterPanel extends JPanel
    {
        int interval = 0;
        int original = 0;
        
        @Override
        protected void paintComponent(Graphics g) 
        {
            super.paintComponent(g);  
            Graphics2D g2 = (Graphics2D) g;
            g2.setStroke(new BasicStroke(3));
            interval = this.getHeight()/8;
            original = interval;
            g2.setColor(new Color(153,153,153));
            
            // Draw all the horizontal (floors) lines.
            for (int i = 0; i<8; i++)
            {
                g2.drawLine(0,interval,this.getWidth(),interval);
                interval += this.getHeight()/8;
            }
            
            // Draw elevator
            g2.setColor(Color.GRAY);
            g2.drawRect((this.getWidth()/2)-20, 
                    (this.getHeight()/8)-(original-5), 
                    40, 
                    original-8);
            
            
        }
    }
    
    // Custom inner class to represent the top left panel.
    // Image is drawn on JPanel (Logo).
    class logoPanel extends JPanel
    {
//        @Override
//        protected void paintComponent(Graphics g) 
//        {
//            super.paintComponent(g);
//            g.drawImage(logo.getImage(), 0, 0, super.getWidth(), super.getHeight(), null);
//        }
    }

}
